zomato:
  outputs:
    dev:
      account: _
      database: ZOMATO
      password: _
      role: DBT_ROLE
      schema: STAGING
      threads: 8
      type: snowflake
      user: _
      warehouse: ZOMATO_WH
  target: dev
